import 'dart:convert';

import 'package:transferencia_bancaria/src/entities/transfers.dart';

// Generated by https://quicktype.io

class TrasnfersModel extends Trasnfers {
  TrasnfersModel(
      {required String idTransaction,
      required int nitUsuario,
      required String fecha,
      required int cuentaOrigen,
      required int cuentaDestino,
      required int monto})
      : super(
            idTransaction: idTransaction,
            nitUsuario: nitUsuario,
            fecha: fecha,
            cuentaOrigen: cuentaOrigen,
            cuentaDestino: cuentaDestino,
            monto: monto);

  Map<String, dynamic> toMap() {
    return {
      'idTransaction': idTransaction,
      'nitUsuario': nitUsuario,
      'fecha': fecha,
      'cuentaOrigen': cuentaOrigen,
      'cuentaDestino': cuentaDestino,
      'monto': monto,
    };
  }

  factory TrasnfersModel.fromMap(Map<String, dynamic> map) {
    return TrasnfersModel(
      idTransaction: map['idTransaction'] ?? '',
      nitUsuario: map['nitUsuario']?.toInt() ?? 0,
      fecha: map['fecha'] ?? '',
      cuentaOrigen: map['cuentaOrigen']?.toInt() ?? 0,
      cuentaDestino: map['cuentaDestino']?.toInt() ?? 0,
      monto: map['monto']?.toInt() ?? 0,
    );
  }

  String toJson() => json.encode(toMap());

  factory TrasnfersModel.fromJson(String source) =>
      TrasnfersModel.fromMap(json.decode(source));
}
